version: "3"
services:
  # client:
  #   image: full-stack-client
  #   build:
  #     context: ./client
  #   ports:
  #     - "3001:3000"
  #   environment:
  #     - REACT_APP_API_URL=http://localhost:5001/api
  #   depends_on:
  #     - server
  #   volumes:
  #     - ./client:/app/
  #     - /app/node_modules
  server:
    image: full-stack-server
    build:
      context: ./server
    ports:
      - "5001:5001"
    environment:
      - PGDATABASE=postgres
      - PGHOST=db
      - PGUSER=postgres
      - PGPASSWORD=password
      - PGPORT=5432
    depends_on:
      - db
    volumes:
      - ./server:/app/
      - /app/node_modules
  db:
    image: full-stack-db
    build:
      context: ./db
    volumes:
      - full-stack-v1:/var/lib/postgresql/data
    ports:
      - "5433:5432"
volumes:
  full-stack-v1:
